// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/river-hebrew-review/Review.tsx": () => import("../components/mockups/river-hebrew-review/Review.tsx")
};
